### ISSUE TITLE
Get color sensor working to detect red/blue balls

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2022-Rapid-React#11]
Have code to control two REV color sensors such that:

- [ ] We can select between either one
- [ ] We can reliably detect when a ball is in the indexer using the proximity sensor
- [ ] We can reliably detect whether the ball is red or blue
- [ ] Create test plan

**Comment by ryan-huang1** [comment]
Docs + Examples 

[Docs](https://codedocs.revrobotics.com/java/com/revrobotics/package-summary.html)
[Example Code](https://github.com/REVrobotics/Color-Sensor-v3-Examples/tree/master/Java)

**Comment by akiyeng2** [comment]
Product: https://www.revrobotics.com/rev-31-1557/

**Comment by fategg555** [comment]
V3 looking good, working on V2
