### ISSUE TITLE
Fix drivebase stuttering issue

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2022-Rapid-React#16]
Comment with debugging ideas and what's worked/not worked

**Comment by ryan-huang1** [comment]
![Image from iOS (4)](https://user-images.githubusercontent.com/59319094/151841915-fbf5adea-dfb0-4433-aa2d-8020be6fcf31.jpg)

[dslog link](https://drive.google.com/file/d/1mwwSmajIjXijePAr7ugUr7OloT9WWPmH/view?usp=sharing)

**Comment by ryan-huang1** [comment]
Hasn't been seen in a week of testing
