### ISSUE TITLE
Create Indexer code

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2022-Rapid-React#20]
- [x] Discuss requirements and specifics of control scheme with design/mechanical
- [x] Create manual control code for two motors
- [x] Discuss color sensing placement with mechanical and electrical team
- [x] Create code/electronics for one v3+one v2 or two v3s
- [x] Create code for upper and lower indexer motors
- [x] Create test plan

**Comment by sjiyeng** [comment]
Eventually it would be nice to have the setpoint of the upper tower belts to be the feed speed into the shooter, but that's quite low priority at the moment

**Comment by sjiyeng** [comment]
We need a current limit of 30A on the upper section because baby neos tend to get smoky without them

**Comment by clairet0** [comment]
Test plan for indexer:

1. test intake and indexer combination, ensuring that the ball indexes at the right speed + accuracy consistently across intake speeds
2. test indexing with sensor
