### ISSUE TITLE
Intake wheel speed 2x Drivebase wheel speed

### ISSUE THREAD

**Issue by ryan-huang1** [Team-4795/2022-Rapid-React#25]

**Comment by fategg555** [comment]
Idk abt 2x speed, although being proportional to db is still fine (0% db speed = 80% intake, 100% --> 40%). Should do some models to test but not super important atm.

**Comment by ryan-huang1** [comment]
"2 times is the rule in general. I got it from Toonie, Toonie got it from chief" -Srinivas 2022

**Comment by ryan-huang1** [comment]
If we are going with the 2x relation then the code should be done
