### ISSUE TITLE
Create intake code

### ISSUE THREAD

**Issue by anatheiguana** [Team-4795/2022-Rapid-React#3]

**Comment by akiyeng2** [comment]
Followup task for week of 1/23 - test this

**Comment by sjiyeng** [comment]
At some point we will need to be varying the intake speed based off drivebase speed, I can work with you on figuring out the constant to multiply the % out by

**Comment by akiyeng2** [comment]
> At some point we will need to be varying the intake speed based off drivebase speed, I can work with you on figuring out the constant to multiply the % out by

@ryan-huang1 to continue with this
