### ISSUE TITLE
3-4 Ball auto paths

### ISSUE THREAD

**Issue by fategg555** [Team-4795/2022-Rapid-React#51]
Create 3 versions of 3 ball auto and 2 versions of 4 ball. Will assess at a later date.

**Comment by ryan-huang1** [comment]
Plan for 3 ball for now is to have it extend the current three ball path

Adding in human player bowling in the ball is a possibility

**Comment by fategg555** [comment]
Do you still have that 3 ball path that goes to feeder station? The 4th ball will be the one that the human player rolls. Also build a path that goes to feeder station and also to the ball close to wall. This gives us 5 ball if done right.
