### ISSUE TITLE
Characterization and Path planning

### ISSUE THREAD

**Issue by akiyeng2** [Team-4795/2022-Rapid-React#7]
- Follow path for pre-drawn auto routine to do a two-ball auto routine
- Troubleshoot Romi path planning
- Do robot characterization
- Troubleshoot on robot
- Generate pathweaver 
- Add Glass visualization

**Comment by ryan-huang1** [comment]
Path following is consistent within 3 inches on tile with 4 tests run back to back. This should improve with better constants and on carpet however this is sufficient for our purposes.
